title: Title_config.yml
description: > # this means to ignore newlines until "baseurl:"
  Description_config.yml
baseurl: "" # the subpath of your site, e.g. /blog
url: "Your-Link.github.io" # the base hostname & protocol for your site
# Build settings
markdown: kramdown

facebook: facebook_config.yml
  app_id: app_id_config.yml

logo: "../css/2016_style/img/icon-large.png"

social: 
  name: name_facebook_config.yml
  link: "https://www.facebook.com/"

google_site_verification: googleXXXXXXXXXXXXXXXX.html

include: ['_2016_pages', '_2017_pages']

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/REAstrono
  - title: twitter
    url: https://twitter.com/REAstrono

# Build settings
markdown: kramdown
permalink: pretty
